apiVersion: v1
kind: ConfigMap
metadata:
  name: metrictemplate2
data: 
 Template: ISDTemplate
 TemplateType: Metric
 Json: |
  {
   "filterKey": "${namespace_key},${pod_key},${app_name}",
   "data": {
     "percent_diff_threshold": "hard",
      "isNormalize": false,
      "groups": [
       {
        "metrics": [
          {
            "metricType": "ADVANCED",
            "metricWeight": 1,
            "nanStrategy": "Remove",
            "accountName": "myprom",
            "riskDirection": "Higher",
            "customThresholdHigher": 100,
            "name": "sum(container_memory_usage_bytes{namespace=\"${namespace_key}\", pod=~\".*${pod_key}.*\"})",
            "criticality": "Normal",
            "customThresholdLower": 100,
            "watchlist": true
          }
        ],
        "group": "Memory Usage"
      },
       {
        "metrics": [
          {
            "metricType": "ADVANCED",
            "metricWeight": 1,
            "nanStrategy": "Remove",
            "accountName": "myprom",
            "riskDirection": "Higher",
            "customThresholdHigher": 80,
            "name": "sum(container_cpu_usage_seconds_total{namespace=\"${namespace_key}\", pod=~\".*${pod_key}.*\"})",
            "criticality": "Normal",
            "customThresholdLower": 80,
            "watchlist": true
          }
        ],
        "group": "CPU Usage"
      },
      {
        "metrics": [
          {
            "metricType": "ADVANCED",
            "metricWeight": 1,
            "nanStrategy": "Remove",
            "accountName": "myprom",
            "riskDirection": "Lower",
            "customThresholdHigher": 80,
            "name": "sum(rate(http_server_requests_seconds_count{kubernetes_namespace=\"${namespace_key}\", kubernetes_pod_name=~\".*${pod_key}.*\"}[1m]))",
            "criticality": "Normal",
            "customThresholdLower": 80,
            "watchlist": true
          }
        ],
        "group": "Throughput"
      },
      {
        "metrics": [
          {
            "metricType": "ADVANCED",
            "metricWeight": 1,
            "nanStrategy": "Remove",
            "accountName": "myprom",
            "riskDirection": "HigherOrLower",
            "customThresholdHigher": 80,
            "name": "(sum(rate(http_server_requests_seconds_count{kubernetes_pod_name=~'.*${pod_key}.*', status=~'^[45]..$', kubernetes_namespace='${namespace_key}'}[1m])) / sum(rate(http_server_requests_seconds_count{ kubernetes_pod_name=~'.*${pod_key}.*', kubernetes_namespace='${namespace_key}'}[1m]))) * 60",
            "criticality": "Normal",
            "customThresholdLower": 80,
            "watchlist": true
          }
        ],
        "group": "Error Rate"
      },
      {
        "metrics": [
          {
            "metricType": "ADVANCED",
            "metricWeight": 1,
            "nanStrategy": "Remove",
            "accountName": "myprom",
            "riskDirection": "HigherOrLower",
            "customThresholdHigher": 80,
            "name": "histogram_quantile(0.95, sum by (le) (rate(http_server_requests_seconds_bucket{kubernetes_pod_name=~'.*${pod_key}.*'}[1m])))",
            "criticality": "Normal",
            "customThresholdLower": 80,
            "watchlist": true
          }
        ],
        "group": "95th Latency"
      }      
    ]
  },
  "templateName": "metrictemplate2",
  "isEdit": true,
  "advancedProvider": "PROMETHEUS",
  "versionNo": ""
  }
