kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: tmpl-gitops
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: canary-score
      count: 1
      initialDelay: 10s    
      provider:
        opsmx:
          profile: opsmx-profile
          gateUrl: https://oea.ryzon7-argo.opsmx.org/
          application: srini-roll-app-of-apps
          user: admin
          lifetimeMinutes: 3
          gitops: true
          threshold:
            pass: 60
            marginal: 40   
          services:
          - metricTemplateName: "metrictemplate2"
            metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
            baselineMetricScope: "opsmx-demo,{{args.baseline-hash}},tmpl-gitops"
            canaryMetricScope: "opsmx-demo,{{args.canary-hash}},tmpl-gitops"
            logTemplateName: "logtemplate3"  
            logScopeVariables: "kubernetes.pod_name"
            baselineLogScope: ".*{{args.baseline-hash}}.*"
            canaryLogScope: ".*{{args.canary-hash}}.*"
                      
